
server:
    port: 8045

spring:
     datasource:
        url: jdbc:mysql://120.79.23.207:3306/springboot?characterEncoding=utf8&useSSL=false
        username: root
        password: root
        druid:
            url: jdbc:mysql://120.79.23.207:3306/springboot?characterEncoding=utf8&useSSL=false
            username: root
            password: root
            initial-size: 2
            max-active: 50
            min-idle: 5
            max-wait: 60000 # 60s
            pool-prepared-statements: true
            max-open-prepared-statements: 20
            validation-query: SELECT 'x' FROM DUAL
            validation-query-timeout: 60 # 60s
            test-on-borrow: false
            test-on-return: false
            test-while-idle: true
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 60000
            max-evictable-idle-time-millis: 60000
            filters: stat,wall
            # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
            web-stat-filter:
                enabled: true
                # url-pattern:
                # exclusions:
                # session-stat-enable: true
                # session-stat-max-count:
                # principal-session-name:
                # principal-cookie-name:
                # profile-enable:
            # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
            stat-view-servlet:
                enabled: true
                # url-pattern:
                reset-enable: false
                login-username: druid
                login-password: druid
     redis:
       host: 120.79.23.207
       port: 16379
       timeout: 5000

mybatis-plus:
        # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
        # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
        mapper-locations: classpath*:/mapper/*Mapper.xml
        #实体扫描，多个package用逗号或者分号分隔
        typeAliasesPackage: com.sdyin.boot.model
        global-config:
          #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
          id-type: 0
          #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
          field-strategy: 1
          #驼峰下划线转换
          db-column-underline: true
          #mp2.3+ 全局表前缀 mp_
          #table-prefix: mp_
          #刷新mapper 调试神器
          #refresh-mapper: true
          #数据库大写下划线转换
          #capital-mode: true
        configuration:
          #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
          map-underscore-to-camel-case: true
          cache-enabled: false
          #配置JdbcTypeForNull, oracle数据库必须配置
          jdbc-type-for-null: 'null'


